#!/usr/bin/env ansible-playbook -i localhost,
---
- name: test output
  hosts: localhost
  gather_facts: no
  vars:
      ansible_connection: local
  tasks:

    - name: 2 lines on stdout and 2 on stderr with rc=0
      shell: seq 200 201; >&2 seq 400 401

    - name: 2 lines on stdout and 2 on stderr with rc=1
      shell: seq 200 201; >&2 seq 400 401; exit 1
