#!/bin/bash
#set -ex
mkdir -p output
for FORMAT in default debug dense json junit minimal oneline profile_tasks selective skippy timer tree
do
  for VERBOSITY in 0 1 2 3 4
  do
    FOLDER="${FORMAT}_v${VERBOSITY}"
     #/$VERBOSITY
    ANSIBLE_STDOUT_CALLBACK=$FORMAT ANSIBLE_VERBOSITY=$VERBOSITY ./sample-a.yml >output/${VERBOSITY}-${FORMAT}.log 2>&1 &
  done
done
wait
