#!/bin/bash
set -eou pipefail
mkdir -p output
rm -rf output/*
for FORMAT in actionable default debug dense json junit minimal null oneline profile_roles profile_tasks selective skippy stderr timer tree unixy yaml
do
  for VERBOSITY in 0 1 2 3 4
  do
    FOLDER="output/${VERBOSITY}"
    mkdir -p $FOLDER
    ANSIBLE_STDOUT_CALLBACK=$FORMAT ANSIBLE_VERBOSITY=$VERBOSITY ./sample-a.yml 2>&1 | ansi2html > ${FOLDER}/${FORMAT}.log.html 2>&1 &
  done
done
wait
